apiVersion: crd.antrea.io/v1beta1
kind: NetworkPolicy
metadata:
  name: egress-policy
  namespace: lfx-mentorship
spec:
  priority: 1
  appliedTo:
    - podSelector: {}
  egress:
    - action: Allow
      to:
        - namespaceSelector: {}
    - action: Allow
      to:
        - fqdn: api.github.com
    - action: Reject
